# Generated by Django 5.1.1 on 2024-10-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="description_course",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="title_course",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="description_lesson",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="title_lesson",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
